### ISSUE TITLE
can you make video tutorial how to install 

### ISSUE THREAD

**Issue by bobwatcherx** [SKbarbon/Flet_StoryBoard#15]
i follow but not work

**Comment by bobwatcherx** [comment]
root@boo-HP-Convertible-x360-11-ab1XX:/home/boo# touch myUI.fletsb
root@boo-HP-Convertible-x360-11-ab1XX:/home/boo# python3 -m fletsb.edit myUI.fletsb
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/fletsb/edit.py", line 60, in <module>
    mainPage(full_path)
  File "/usr/local/lib/python3.10/dist-packages/fletsb/pages/main_page.py", line 31, in __init__
    self.dict_content = json.loads(open(file_path, encoding="utf-8").read())
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by maxcm01** [comment]
not working, maybe a tutorial would be helpfull

**Comment by LemonFan-maker** [comment]
Try this?
```bash
python3 -m  Flet_StoryBoard.edit
```
