### ISSUE TITLE
Error with recent versions of flet on Windows 

### ISSUE THREAD

**Issue by vargasmiguel** [SKbarbon/Flet_StoryBoard#4]
Exception in thread Thread-12:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flet\event_handler.py", line 16, in handler
    h(r)
  File "C:\ProgramData\Anaconda3\lib\site-packages\Flet_StoryBoard\createStoryBoard.py", line 199, in __page_two
    win_theme = window_theme (mainc)
  File "C:\ProgramData\Anaconda3\lib\site-packages\Flet_StoryBoard\createStoryBoard.py", line 265, in window_theme
    flet.Row(controls=[
  File "C:\ProgramData\Anaconda3\lib\site-packages\flet\row.py", line 131, in __init__
    self.alignment = alignment
  File "C:\ProgramData\Anaconda3\lib\site-packages\flet\row.py", line 171, in alignment
    self.__set_alignment(value)
  File "<@beartype(flet.row.Row.__set_alignment) at 0x14694968e50>", line 46, in __set_alignment
beartype.roar.BeartypeCallHintParamViolation: @beartyped flet.row.Row.__set_alignment() parameter ←[33mvalue='left'←[0m violates type hint ←[1m←[34mtyping.Literal[None, 'start', 'end', 'center', 'spaceBetween', 'spaceAround', 'spaceEvenly']←[0m, as ←[1m←[31mstr←[0m ←[33m'left'←[0m != None, 'start', 'end', 'center', 'spaceBetween', 'spaceAround', or 'spaceEvenly'.

**Comment by SKbarbon** [comment]
New version juat releasd. Please upgrade with hope that it fixed your problem.
